version: "3.9"
services:
  core-db:
    image: "mariadb:10.10-jammy"
    environment:
      - MARIADB_ROOT_PASSWORD=aldim
      - MARIADB_DATABASE=core
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MARIADB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
  core:
    build: ./core
    depends_on:
      core-db:
        condition: service_healthy
    volumes:
      - ./core:/core:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6565/checkserverrun"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "6565:6565"
  kms-db:
    image: "mariadb:10.10-jammy"
    environment:
      - MARIADB_ROOT_PASSWORD=aldim
      - MARIADB_DATABASE=kms
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MARIADB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
  kms:
    build: ./kms
    depends_on:
      kms-db:
        condition: service_healthy
      core:
        condition: service_healthy
    volumes:
      - ./kms:/kms:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5656/checkserverrun"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5656:5656"
  frontend:
    build: ./frontend
    depends_on:
      kms-db:
        condition: service_healthy
      core:
        condition: service_healthy
      kms:
        condition: service_healthy
    ports:
      - "3000:3000"
  solr:
    image: "solr:9.2.0"
    ulimits:
      nofile:
        soft: 65000
        hard: 65000
    volumes:
      - ./solr:/var/solr
    ports:
      - "8983:8983"
    user: root 
    command: bash -c "chown -R 8983:8983 /var/solr && runuser -u solr -- solr-foreground"
  tika:
    image: "apache/tika:2.7.0.1-full"
    ports:
      - "9998:9998"
    restart: always