import '../../styles/globals.css';

export const metadata = {
  title: 'Login',
  description: 'Generated by create next app',
};

export default function TestLayout({ children }) {
  return <section>{children}</section>;
}
