version: "3.9"
services:
  core:
    build: .
    depends_on:
      core-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MARIADB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "6565:6565"
    # volumes:
    #   - ./:/core:rw
  core-db:
    image: "mariadb:10.10-jammy"
    environment:
      - MARIADB_ROOT_PASSWORD=aldim
      - MARIADB_DATABASE=core
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MARIADB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
