version: "3.9"
services:
  kms-db:
    image: "mariadb:10.10-jammy"
    environment:
      - MARIADB_ROOT_PASSWORD=aldim
      - MARIADB_DATABASE=kms
  kms:
    build: .
    depends_on:
      - kms-db
    volumes:
      - ./:/kms:rw
    command: /bin/sh -c "while true; do sleep 100000; done"
    ports:
      - "5656:5656"
  tika:
    image: "apache/tika:2.7.0.1-full"
    ports:
      - "9998:9998"
    restart: always
  solr:
    image: "solr:9.2"
    ports:
      - "8983:8983"
    restart: always